apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: morgrynn/movies
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: fitflexevents
            - name: MONGO_URI
              value: 'mongodb://movies-mongo-srv:27017/movies'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: movies-srv
spec:
  selector: 
    app: movies
  ports:
    - name: movies
      protocol: TCP
      port: 3000
      targetPort: 3000